### ISSUE TITLE
monitorHeadStream is not a function

### ISSUE THREAD

**Issue by yongzhihuang** [sebinsua/monitor-head-stream#1]
I'm getting this when I run the example, any idea?

```
onst createStream = () => new TimelineStream('POTUS')
const indexBy = obj => obj.id
const skipWhenPinned = obj => obj.isPinned === true

pump(
  monitorHeadStream(createStream, indexBy, skipWhenPinned),
  JSONStream.stringify('[\n', ',\n', '\n]\n'),
  process.stdout
)
```

```
 monitorHeadStream(createStream, indexBy, skipWhenPinned),
  ^

TypeError: monitorHeadStream is not a function
    at Object.<anonymous> (/Users/usw/code/test/liquidation.js:43:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
```

**Comment by adamcoulombe** [comment]
Same issue
